[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[dev]
  command = "npm start"
  framework = "create-react-app"
  port = 8888
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true